### ISSUE TITLE
Installing, npm publish?, version

### ISSUE THREAD

**Issue by tcrowe** [curbengh/hexo-yam#19]
`v2.2.1` is the latest version of this package on npmjs registry. But I would like this `v3` you have made.

Is it best to install from github? Other?

Thank you 👍🏻

**Comment by curbengh** [comment]
🤔 `3.1.0` is tagged as "latest".

![npm](https://user-images.githubusercontent.com/43627182/66015034-356bb780-e510-11e9-8361-d449092278ed.png)

**Comment by tcrowe** [comment]
Oh, thank you. Actually what happened was that this information was cached here locally on my [verdaccio](https://github.com/verdaccio/verdaccio).

Solved! :D
