### ISSUE TITLE
Consider switching to minify-xml for XML compression

### ISSUE THREAD

**Issue by kristian** [curbengh/hexo-yam#24]
I saw you are using the XML regex from pretty-data, as many do. Unfortunately the regex compression from pretty-data is pretty rudimentary. For this reason I created an own package called [minify-xml](https://www.npmjs.com/package/minify-xml), which you might want to consider switching to. It not only covers the minifications of pretty-data, but also rightfully respects CDATA tags, as well as does many more "in-tag" minifications, such as removing whitespaces between attributes and removing unused XML 1.1 namespaces.

**Comment by curbengh** [comment]
awesome, I particularly like how CDATA is retained.
