### ISSUE TITLE
inline ES6

### ISSUE THREAD

**Issue by njzjz** [curbengh/hexo-yam#30]
`html-minifier` doesn't support minifying inline ES6 script. How about using `html-minifier-terser`?

**Comment by curbengh** [comment]
html-minifier-terser uses [terser v4](https://github.com/terser/html-minifier-terser/blob/5fd0679f5107b5d9104994a1c6b73b9df830df8b/package.json#L65) instead of [v5](https://www.npmjs.com/package/terser/v/5.6.1).
